### ISSUE TITLE
_debug.scss warns about empty hr's

### ISSUE THREAD

**Issue by Inkdpixels** [csswizardry/inuit.css#100]
The _debugs.scss file will outline any `<hr>` as they are "empty" elements - As I dont think this was intended to be displayed, a proper solution would be to use the :not selector.

``` css
:empty:not(hr){
    outline:5px solid yellow;
}
```
