### ISSUE TITLE
<nav ...>, .nav ?

### ISSUE THREAD

**Issue by wiesson** [csswizardry/inuit.css#14]
http://www.w3schools.com/html5/html5_reference.asp

maybe its usefull changing the nav-tag for html5 markup? 

``` css
.nav, nav {
    list-style:none;
}
.nav li, nav li {
    display:inline;
}
.nav a, nav a {
    display:inline-block;
}
```

regards
