### ISSUE TITLE
Configurable direction to support RTL

### ISSUE THREAD

**Issue by imranomari** [csswizardry/inuit.css#140]
There are many cases where RTL support become a necessity, I think a good framework as Inuit should -and could- facilitate the switch between RTL and LTR, my suggestion is to avoid using 'left' and 'right' and use variables instead:

Rather than

``` scss
ul, ol, dd {
  margin-left: 48px;
  margin-left: 3rem;
}
//..
.g,
.grid {
  float: left;
  padding-left: 24px;
}
//..
.flush--right   { margin-right: 0!important; }
.flush--left    { margin-left:  0!important; }
```

We could define variables as:

``` scss
$direction: 'ltr' !default;

$dir-default: 'left';// or $dir-begin, $dir-start, $dir-normal
$dir-rev: 'right';// or $dir-opposite, $dir-end
@if $direction == 'rtl' {
  $dir-default: 'right';
  $dir-rev: 'left';
}
```

And write the code above as:

``` scss
ul, ol, dd {
  margin-#{$dir-default}: 48px;
  margin-#{$dir-default}: 3rem;
}
//..
.g,
.grid {
  float: #{$dir-default};
  padding-#{$dir-default}: 24px;
}

.flush--begin   { margin-#{$dir-default}: 0!important; }
.flush--end    { margin-#{$dir-rev}:  0!important; }
```

What do you think?
