### ISSUE TITLE
h1 .. h6 font-size:1em;

### ISSUE THREAD

**Issue by wiesson** [csswizardry/inuit.css#15]
line 88 to 90

``` css
h1,h2,h3,h4,h5,h6 {
      font-size:1em;
 }
```

simple question, why do you put em to 1em, and later to their real hights?
