### ISSUE TITLE
Flexbox class name conflict with Modernizr

### ISSUE THREAD

**Issue by wingsline** [csswizardry/inuit.css#60]
Modernizr adds a class named 'flexbox' to the html tag on browsers that support flexbox. This renders the layout incorrectly in those browsers.

Workaround:

``` css
html.flexbox{
    display:block;
    width:auto;
}
```

Browsers tested: IE 10 and WebKit r134433
